"""
    Add a logging utility to capture all errors and warnings
    Generated by Tiny Backspace AI Agent with Claude AI
    """

    import logging
    import sys
    import traceback
    from typing import Any, Optional, Dict
    from datetime import datetime

    # Configure logging
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        handlers=[
            logging.FileHandler('error_log.log'),
            logging.StreamHandler(sys.stdout)
        ]
    )

    class ErrorHandler:
        """
        Advanced error handling utility class with logging capabilities.
        Provides comprehensive error tracking, logging, and recovery mechanisms.
        """
        
        def __init__(self, service_name: str = "TinyBackspace"):
            self.service_name = service_name
            self.logger = logging.getLogger(service_name)
            self.error_count = 0
            self.error_history: Dict[str, int] = {}
        
        def log_error(self, error: Exception, context: str = "Unknown", 
                    additional_info: Optional[Dict[str, Any]] = None) -> None:
            """
            Log an error with comprehensive details and context.
            
            Args:
                error: The exception that occurred
                context: Description of where/when the error occurred  
                additional_info: Optional dictionary with extra context
            """
            self.error_count += 1
            error_type = type(error).__name__
            
            # Track error frequency
            self.error_history[error_type] = self.error_history.get(error_type, 0) + 1
            
            # Create detailed error message
            error_details = {
                "timestamp": datetime.now().isoformat(),
                "service": self.service_name,
                "error_type": error_type,
                "error_message": str(error),
                "context": context,
                "error_count": self.error_count,
                "traceback": traceback.format_exc(),
                "additional_info": additional_info or {}
            }
            
            self.logger.error(f"Error in {context}: {error_details}")
        
        def safe_execute(self, func, *args, **kwargs) -> Optional[Any]:
            """
            Execute a function safely with automatic error handling and logging.
            
            Args:
                func: Function to execute safely
                *args: Positional arguments for the function
                **kwargs: Keyword arguments for the function
                
            Returns:
                Function result or None if an error occurred
            """
            try:
                result = func(*args, **kwargs)
                self.logger.info(f"Successfully executed {func.__name__}")
                return result
            except Exception as e:
                self.log_error(e, f"safe_execute({func.__name__})")
                return None
        
        def handle_critical_error(self, error: Exception, context: str = "Critical") -> None:
            """
            Handle critical errors that may require immediate attention.
            
            Args:
                error: The critical exception
                context: Critical error context
            """
            self.log_error(error, f"CRITICAL: {context}")
            
            # In a real application, you might:
            # - Send alerts to monitoring systems
            # - Trigger emergency procedures
            # - Gracefully shut down systems
            
            print(f"🚨 CRITICAL ERROR in {context}: {str(error)}")
        
        def get_error_stats(self) -> Dict[str, Any]:
            """
            Get comprehensive error statistics and health metrics.
            
            Returns:
                Dictionary with error statistics and service health info
            """
            return {
                "service_name": self.service_name,
                "total_errors": self.error_count,
                "error_types": self.error_history,
                "most_common_error": max(self.error_history, key=self.error_history.get) if self.error_history else None,
                "service_health": "degraded" if self.error_count > 10 else "healthy"
            }

    # Example usage and testing
    if __name__ == "__main__":
        # Initialize error handler
        error_handler = ErrorHandler("TinyBackspaceAgent")
        
        # Test error logging
        try:
            # Simulate an error
            result = 1 / 0
        except Exception as e:
            error_handler.log_error(e, "division_test", {"operation": "1/0"})
        
        # Test safe execution
        def risky_function(x, y):
            if y == 0:
                raise ValueError("Cannot divide by zero!")
            return x / y
        
        # This will handle the error gracefully
        safe_result = error_handler.safe_execute(risky_function, 10, 0)
        print(f"Safe execution result: {safe_result}")
        
        # Get error statistics
        stats = error_handler.get_error_stats()
        print(f"Error statistics: {stats}")
        
        print("✅ Error handling utility class is working correctly!")
    